spring.application.name=SmartGrocery
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://dbvm.bass.com.eg/testDataBase
spring.datasource.username=postgres
spring.datasource.password=BASS
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.main.lazy-initialization=true
